// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlfdvVeXf_twKEOCYMmyjJ2orYKXkvtc8',
    appId: '1:528451530175:web:df48a472f2408a4858850a',
    messagingSenderId: '528451530175',
    projectId: 'lost-and-found-app-55c9a',
    authDomain: 'lost-and-found-app-55c9a.firebaseapp.com',
    storageBucket: 'lost-and-found-app-55c9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDltsLa5NigPnSPaB__0ozErlC7ppdpzKs',
    appId: '1:528451530175:android:d9c25cf84a42e00358850a',
    messagingSenderId: '528451530175',
    projectId: 'lost-and-found-app-55c9a',
    storageBucket: 'lost-and-found-app-55c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2auJwnrZ-HXejE0Su1qi7uBisxG96Qgs',
    appId: '1:528451530175:ios:e2d5e7390c638fca58850a',
    messagingSenderId: '528451530175',
    projectId: 'lost-and-found-app-55c9a',
    storageBucket: 'lost-and-found-app-55c9a.appspot.com',
    iosClientId: '528451530175-ta8bu2u2p3oa4poq216j2bniqce3trds.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostfoundapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2auJwnrZ-HXejE0Su1qi7uBisxG96Qgs',
    appId: '1:528451530175:ios:e2d5e7390c638fca58850a',
    messagingSenderId: '528451530175',
    projectId: 'lost-and-found-app-55c9a',
    storageBucket: 'lost-and-found-app-55c9a.appspot.com',
    iosClientId: '528451530175-ta8bu2u2p3oa4poq216j2bniqce3trds.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostfoundapp',
  );
}
